import { Theme } from './types'

// 🌟 Temas predefinidos profesionales
export const THEMES: Record<string, Theme> = {
  elegante: {
    id: 'elegante',
    name: 'Elegante',
    preview: '/themes/elegante-preview.png',
    colors: {
      primary: '#1E293B',
      primaryHover: '#0F172A',
      primaryLight: '#334155',
      secondary: '#EAB308',
      secondaryLight: '#FDE047',
      secondaryDark: '#CA8A04',
      accent: '#F59E0B',
      accentLight: '#FBBF24',
      accentDark: '#D97706',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      text: '#1E293B',
      textMuted: '#64748B',
      border: '#E2E8F0',
      success: '#16A34A',
      successBg: '#DCFCE7',
      error: '#DC2626',
      errorBg: '#FEF2F2',
      warning: '#D97706',
      warningBg: '#FFFBEB',
      info: '#0EA5E9',
      infoBg: '#F0F9FF',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '600',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '0.75rem',
      shadowStyle: 'medium',
      buttonStyle: 'rounded',
    },
  },

  natural: {
    id: 'natural',
    name: 'Natural',
    preview: '/themes/natural-preview.png',
    colors: {
      primary: '#16A34A',
      primaryHover: '#15803D',
      primaryLight: '#22C55E',
      secondary: '#A3A3A3',
      secondaryLight: '#D4D4D4',
      secondaryDark: '#737373',
      accent: '#EAB308',
      accentLight: '#FDE047',
      accentDark: '#CA8A04',
      background: '#FEFEFE',
      surface: '#F9FDF9',
      text: '#1F2937',
      textMuted: '#6B7280',
      border: '#E5E7EB',
      success: '#059669',
      successBg: '#ECFDF5',
      error: '#DC2626',
      errorBg: '#FEF2F2',
      warning: '#D97706',
      warningBg: '#FFFBEB',
      info: '#0891B2',
      infoBg: '#F0FDFA',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '500',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '1rem',
      shadowStyle: 'light',
      buttonStyle: 'rounded',
    },
  },

  corporativo: {
    id: 'corporativo',
    name: 'Corporativo',
    preview: '/themes/corporativo-preview.png',
    colors: {
      primary: '#2563EB',
      primaryHover: '#1D4ED8',
      primaryLight: '#3B82F6',
      secondary: '#64748B',
      secondaryLight: '#94A3B8',
      secondaryDark: '#475569',
      accent: '#F59E0B',
      accentLight: '#FBBF24',
      accentDark: '#D97706',
      background: '#FFFFFF',
      surface: '#F1F5F9',
      text: '#1E293B',
      textMuted: '#475569',
      border: '#CBD5E1',
      success: '#059669',
      successBg: '#ECFDF5',
      error: '#DC2626',
      errorBg: '#FEF2F2',
      warning: '#D97706',
      warningBg: '#FFFBEB',
      info: '#0EA5E9',
      infoBg: '#F0F9FF',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '600',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '0.5rem',
      shadowStyle: 'medium',
      buttonStyle: 'sharp',
    },
  },

  femenino: {
    id: 'femenino',
    name: 'Femenino',
    preview: '/themes/femenino-preview.png',
    colors: {
      primary: '#EC4899',
      primaryHover: '#DB2777',
      primaryLight: '#F472B6',
      secondary: '#A855F7',
      secondaryLight: '#C084FC',
      secondaryDark: '#9333EA',
      accent: '#F472B6',
      accentLight: '#FBCFE8',
      accentDark: '#E879F9',
      background: '#FFFBFF',
      surface: '#FDF2F8',
      text: '#1F2937',
      textMuted: '#6B7280',
      border: '#F3E8FF',
      success: '#059669',
      successBg: '#ECFDF5',
      error: '#DC2626',
      errorBg: '#FEF2F2',
      warning: '#D97706',
      warningBg: '#FFFBEB',
      info: '#8B5CF6',
      infoBg: '#F5F3FF',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '500',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '1.5rem',
      shadowStyle: 'light',
      buttonStyle: 'pill',
    },
  },

  moderno: {
    id: 'moderno',
    name: 'Moderno',
    preview: '/themes/moderno-preview.png',
    colors: {
      primary: '#7C3AED',
      primaryHover: '#6D28D9',
      primaryLight: '#8B5CF6',
      secondary: '#1F2937',
      secondaryLight: '#374151',
      secondaryDark: '#111827',
      accent: '#10B981',
      accentLight: '#34D399',
      accentDark: '#059669',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      textMuted: '#6B7280',
      border: '#E5E7EB',
      success: '#10B981',
      successBg: '#ECFDF5',
      error: '#EF4444',
      errorBg: '#FEF2F2',
      warning: '#F59E0B',
      warningBg: '#FFFBEB',
      info: '#06B6D4',
      infoBg: '#F0FDFA',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '700',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '0.375rem',
      shadowStyle: 'heavy',
      buttonStyle: 'sharp',
    },
  },

  clasico: {
    id: 'clasico',
    name: 'Clásico',
    preview: '/themes/clasico-preview.png',
    colors: {
      primary: '#DC2626',
      primaryHover: '#B91C1C',
      primaryLight: '#EF4444',
      secondary: '#1F2937',
      secondaryLight: '#374151',
      secondaryDark: '#111827',
      accent: '#F59E0B',
      accentLight: '#FBBF24',
      accentDark: '#D97706',
      background: '#FFFFFE',
      surface: '#F9FAFB',
      text: '#1F2937',
      textMuted: '#4B5563',
      border: '#D1D5DB',
      success: '#059669',
      successBg: '#ECFDF5',
      error: '#DC2626',
      errorBg: '#FEF2F2',
      warning: '#D97706',
      warningBg: '#FFFBEB',
      info: '#0EA5E9',
      infoBg: '#F0F9FF',
    },
    typography: {
      fontFamily: 'Inter, system-ui, sans-serif',
      headingWeight: '600',
      bodyWeight: '400',
    },
    styling: {
      borderRadius: '0.5rem',
      shadowStyle: 'medium',
      buttonStyle: 'rounded',
    },
  },
}

// Tema por defecto
export const DEFAULT_THEME = THEMES.elegante

// Función para obtener tema por ID
export function getThemeById(id: string): Theme {
  return THEMES[id] || DEFAULT_THEME
}

// Función para obtener lista de temas
export function getAllThemes(): Theme[] {
  return Object.values(THEMES)
}

// Función para generar CSS variables
export function generateThemeCSS(theme: Theme): Record<string, string> {
  return {
    '--color-primary': theme.colors.primary,
    '--color-primary-hover': theme.colors.primaryHover,
    '--color-primary-light': theme.colors.primaryLight,
    '--color-secondary': theme.colors.secondary,
    '--color-secondary-light': theme.colors.secondaryLight,
    '--color-secondary-dark': theme.colors.secondaryDark,
    '--color-accent': theme.colors.accent,
    '--color-accent-light': theme.colors.accentLight,
    '--color-accent-dark': theme.colors.accentDark,
    '--color-background': theme.colors.background,
    '--color-surface': theme.colors.surface,
    '--color-text': theme.colors.text,
    '--color-text-muted': theme.colors.textMuted,
    '--color-border': theme.colors.border,
    '--color-success': theme.colors.success,
    '--color-success-bg': theme.colors.successBg,
    '--color-error': theme.colors.error,
    '--color-error-bg': theme.colors.errorBg,
    '--color-warning': theme.colors.warning,
    '--color-warning-bg': theme.colors.warningBg,
    '--color-info': theme.colors.info,
    '--color-info-bg': theme.colors.infoBg,
    '--font-family': theme.typography.fontFamily,
    '--font-heading-weight': theme.typography.headingWeight,
    '--font-body-weight': theme.typography.bodyWeight,
    '--border-radius': theme.styling.borderRadius,
  }
}